### ISSUE TITLE
Feature Request: Ability to Enable QEMU Guest Agent on VMs during TF deployment

### ISSUE THREAD

**Issue by b0rbb** [verge-io/terraform-provider-vergeio#6]
Request: Ability to enable QEMU Guest Agent for a VM within the specification of a VM resource.

Expected Outcome: VM will be deployed with the QEMU Guest Agent enabled.  The assumption here is that the QEMU Guest Agent is already installed on (or will be immediately installed on) a VM deployed via Terraform.

<img width="408" alt="image" src="https://github.com/user-attachments/assets/76522d69-14de-402b-801a-a320e51ee07e" />

**Comment by jaydwit** [comment]
Guest Agent has been added and can be enabled using a boolean. Docs will be updated and the change will be live during the next tagged release.
